function BGTable() {

    //biggest abomination ever
    return (
        <table style={{transform:"translate(200px,50px)",position:"absolute",zIndex:1,width:"4200.5px"}}>
            <tbody>
                <tr style={{height:"100px",borderBottom:"dashed 1px"}}>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                </tr>
                <tr style={{height:"100px",borderBottom:"dashed 1px"}}>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                </tr>
                <tr style={{height:"100px",borderBottom:"dashed 1px"}}>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                </tr>
                <tr style={{height:"100px",borderBottom:"dashed 1px"}}>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                </tr>
                <tr style={{height:"100px",borderBottom:"dashed 1px"}}>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                </tr>
                <tr style={{height:"100px",borderBottom:"dashed 1px"}}>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                </tr>
                <tr style={{height:"100px",borderBottom:"dashed 1px"}}>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                    <td style={{width:"200px",borderRight:"dashed 1px"}}></td>
                </tr>
            </tbody>
        </table>
    )
}

export default BGTable