version: "3"

services:
  client:
    build:
      context: ./code/client
    ports:
      - "5173:5173"
    networks:
      - kiruna-explorer-net
  server:
    build:
      context: ./code/server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./code/server/src/db:/app/src/db
    networks:
      - kiruna-explorer-net

networks:
  kiruna-explorer-net:
    driver: bridge
