version: "1"

services:
  client:
    build:
      context: ./code/client
    ports:
      - "3000:3000"
    networks:
      - kiruna-explorer-net
  server:
    build:
      context: ./code/server
    ports:
      - "3001:3001"
    volumes:
      - ./code/server/src/db:/app/src/db
    networks:
      - kiruna-explorer-net

networks:
  kiruna-explorer-net:
    driver: bridge
